[local]
localhost

[mangodb]
mangodb.sujitha-daws.online

[redis]
redis.sujitha-daws.online

[mysql]
redis.sujitha-daws.online

[rabbitmq]
redis.sujitha-daws.online

[redis]
redis.sujitha-daws.online

[redis]
redis.sujitha-daws.online

[redis]
redis.sujitha-daws.online

[redis]
redis.sujitha-daws.online